name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  with-checkout-job:
    name: With Checkout
    runs-on: 'ubuntu-latest'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4  
      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .
      - name: build
        run: |
          pip install --upgrade build
          python -m build
          tree .

      - name: artifact creation
        run: |
          mv script.py dist/script.py
          cd dist
          rm my_package-0.0.0.tar.gz
          ls

      
          
        
