name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    with-checkout-job:
        name: With Checkout
        runs-on: 'ubuntu-latest'
        needs: without-checkout-job
        steps:
        - name: Git Checkout
            uses: actions/checkout@v4
        - name: Install tree & run
            run: |
            sudo apt-get install -y tree
            tree .
